### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Liz-F** [simeonf/readaloud#15]
There need to be ways to filter and separate the books (genre, age range, enjoyment, etc.). There should not just be a huge long list of book titles.

**Comment by simeonf** [comment]
Splitting this into two features: 

1. We need to be able to add categories to books and see them.
2. We need to be able to search and filter books. 

The second part is a separate issue because we'll want to search/filter by other things than categories - like book title, author, age, etc. As much as possible we want to keep issues to a single item of work so if we already had a search page we might say it's one issue to add categories in the admin, make them show up on the site, and enable search. But since we don't have search yet I split this part out into #20
